-- WingMan — production schema safety migration
-- ------------------------------------------------------------------
-- Idempotent. Safe to run any number of times in the Neon SQL Editor.
-- It guarantees production has every table and column the app queries:
--   categories, menu_items (dual pricing + available), offers (active),
--   site_settings. Existing data is never modified or dropped.
--
-- HOW TO RUN:
--   1. Open the Neon Console -> your project -> SQL Editor.
--   2. Paste this entire file and click "Run".
--   3. Re-run the production admin flow; new items/offers now appear publicly.
-- ------------------------------------------------------------------

-- ---------- categories ----------
CREATE TABLE IF NOT EXISTS categories (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL UNIQUE,
  sort_order  INTEGER NOT NULL DEFAULT 99,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS categories_sort_idx ON categories (sort_order, id);

-- ---------- menu_items (with dual pricing + availability) ----------
CREATE TABLE IF NOT EXISTS menu_items (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL,
  description TEXT    NOT NULL DEFAULT '',
  price_usd   NUMERIC(10, 2),
  price_lbp   NUMERIC(14, 2),
  category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL,
  image_url   TEXT    NOT NULL DEFAULT '',
  available   BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 99,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now(),
  updated_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

-- Backfill any columns that may be missing on an older production table.
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS description TEXT    NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS price_usd   NUMERIC(10, 2);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS price_lbp   NUMERIC(14, 2);
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS category_id BIGINT REFERENCES categories(id) ON DELETE SET NULL;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS image_url   TEXT    NOT NULL DEFAULT '';
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS available   BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS sort_order  INTEGER NOT NULL DEFAULT 99;
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS created_at  TIMESTAMPTZ NOT NULL DEFAULT now();
ALTER TABLE menu_items ADD COLUMN IF NOT EXISTS updated_at  TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS menu_items_sort_idx     ON menu_items (sort_order, id);
CREATE INDEX IF NOT EXISTS menu_items_category_idx ON menu_items (category_id);

-- ---------- offers (with active flag) ----------
CREATE TABLE IF NOT EXISTS offers (
  id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name        TEXT    NOT NULL DEFAULT '',
  image_url   TEXT    NOT NULL,
  price_usd   NUMERIC(10, 2),
  price_lbp   NUMERIC(14, 2),
  active      BOOLEAN NOT NULL DEFAULT TRUE,
  sort_order  INTEGER NOT NULL DEFAULT 99,
  created_at  TIMESTAMPTZ NOT NULL DEFAULT now()
);

ALTER TABLE offers ADD COLUMN IF NOT EXISTS name       TEXT    NOT NULL DEFAULT '';
ALTER TABLE offers ADD COLUMN IF NOT EXISTS price_usd  NUMERIC(10, 2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS price_lbp  NUMERIC(14, 2);
ALTER TABLE offers ADD COLUMN IF NOT EXISTS active     BOOLEAN NOT NULL DEFAULT TRUE;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS sort_order INTEGER NOT NULL DEFAULT 99;
ALTER TABLE offers ADD COLUMN IF NOT EXISTS created_at TIMESTAMPTZ NOT NULL DEFAULT now();

CREATE INDEX IF NOT EXISTS offers_sort_idx ON offers (sort_order, id);

-- ---------- site_settings (single row) ----------
CREATE TABLE IF NOT EXISTS site_settings (
  id               INTEGER PRIMARY KEY DEFAULT 1,
  whatsapp_number  TEXT NOT NULL DEFAULT '',
  whatsapp_message TEXT NOT NULL DEFAULT 'Hi WingMan! I would like to place an order.',
  phone_number     TEXT NOT NULL DEFAULT '',
  instagram_url    TEXT NOT NULL DEFAULT '',
  working_hours    TEXT NOT NULL DEFAULT '',
  delivery_areas   TEXT NOT NULL DEFAULT '',
  updated_at       TIMESTAMPTZ NOT NULL DEFAULT now(),
  CONSTRAINT site_settings_singleton CHECK (id = 1)
);

INSERT INTO site_settings (id) VALUES (1)
ON CONFLICT (id) DO NOTHING;
